version: '3'

volumes:

  school-pg-data: {}
  school-rabbitmq-data: {}

services:

  school-postgres:
    image: sameersbn/postgresql:10-1
    restart: always
    environment:
      DB_NAME: school-query,school-core
      DB_USER: dev-school
      DB_PASS: dev-school
      PG_PASSWORD: totvs@123
    ports:
      - 15432:5432
      - 5432:5432
    volumes:
      - school-pg-data:/var/lib/postgresql

  school-pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dev-school@totvs.com.br
      PGADMIN_DEFAULT_PASSWORD: dev-school
    ports:
      - 8989:80

  school-rabbitmq:
    image: rabbitmq:3.7.7-management
    volumes:
      - school-rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
#  cash-rac:
#image: docker.totvs.io/tnf/rac:1.6
#ports:
#- 80:80
#command: "cd /app && /entry.sh"
#environment:
#ApplicationUser: postgres
#DefaultConnectionString: PostgreSQL
#Migrator_ConnectionStrings__PostgreSQL: Data Source=cash-postgres;Port=5432;Database=TOTVSRAC;User ID=postgres;password=totvs@123;Unicode=true;
#ConnectionStrings__PostgreSQL: Data Source=cash-postgres;Port=5432;Database=TOTVSRAC;User ID=postgres;password=totvs@123;Unicode=true;
#RunMigrator: T
# Hosts: cash-postgres(ip do docker) abc.rac.totvs.com.br
#HostUrl: http://*.rac.totvs.com.br/totvs.rac
